# Ayudantía 1

In [1]:
import numpy as np
import scipy.linalg as LA
import matplotlib.pyplot as plt

## Problema 1: Cómo evitar perdida de información por cancelación.

Queremos calcular las raíces del polinomio:

$$p(x)=x^{2}-56x + 1$$

Sabemos, por álgebra de colegio, que sus raíces son:

$$x_{1,2}=28 \pm \sqrt{783}$$

Esta solución es la que se conoce como solución exacta. En particular, para calcularlas habrá que aproximar $\sqrt{783}$ por algún valor numérico. Tomaremos la siguiente aproximación como demostración:

$$\sqrt{783}\approx 27.982 (\pm 0.0001)$$

### Calcule los errores relativos que se obtienen con esta aproximación

In [2]:
raiz_1 = 28 + np.sqrt(783)
raiz_2 = 28 - np.sqrt(783) #Asumiremos estas raíces calculadas como las más certeras

In [3]:
x1 = 28 + 27.982
x2 = 28 - 27.982

print("Error absoluto raíz 1: ")
print(f"{abs(raiz_1-x1):.4f}")

print("Error absoluto raíz 2:")
print(f"{abs(raiz_2-x2):.4f}")

Error absoluto raíz 1: 
0.0001
Error absoluto raíz 2:
0.0001


In [4]:
print("Error relativo raíz 1: ")
print(f"{abs(raiz_1-x1)/abs(raiz_1):.2e}")

print("\nError relativo raíz 2: ")
print(f"{abs(raiz_2-x2)/abs(raiz_2):.2e}")

Error relativo raíz 1: 
2.45e-06

Error relativo raíz 2: 
7.68e-03


Notamos inmediatamente que el error relativo difiere en un orden de $10^{3}$ entre ambas soluciones. Nos gustaría que esto no fuera así. Para esto revisaremos formas de cómo evitar esto.

### Utilice su conocimiento sobre polinomios de grado 2 para encontrar otra fórmula para calcular $x_2$, la raíz que tiene mayor error relativo.

Tenemos que para polinomios de grado 2 se cumple la siguiente relación:

$$x_1x_2=c$$

Con esto, tenemos lo siguiente:

$$x_2=\frac{c}{x_1}$$

Que para el caso que estudiamos significa que:

$$x_2 = \frac{1}{x_1}$$

El cálculo de $x_2$ por este método es ventajoso ya que el error relativo se acota en términos del error relativo en $x_1$. Veamos esto:

In [5]:
x21 = 1/x1
print("Error absoluto raíz 2: ")
print(f"{abs(raiz_2-x21):.2e}")

print("\nError relativo raíz 2: ")
print(f"{abs(raiz_2-x21)/abs(raiz_2):.2e}")

Error absoluto raíz 2: 
4.38e-08

Error relativo raíz 2: 
2.45e-06


### Revise el valor de $x_2$ y encuentre una forma de representarlo sin usar restas.

Vemos que:

$$\begin{align*}
x_2=
28-\sqrt{783} 
&= \sqrt{784}-\sqrt{783}\\
&=\frac{\sqrt{784}-\sqrt{783}}{\sqrt{784}+\sqrt{783}}(\sqrt{784}+\sqrt{783})\\
&=\frac{784-783}{\sqrt{784}+\sqrt{783}}\\
&=\frac{1}{28+\sqrt{783}} = \frac{1}{x_1}
\end{align*}$$

Es decir, obtenemos la misma formula revisada anteriormente, y ya sabemos como mejora el error relativo obtenido.

### Utilice series de Taylor para aproximar la raíz problemática.

Vemos la función $f(x)=\sqrt{x}$ y su serie de Taylor:

$$f(x+h) = f(x) + f'(x)h + \frac{1}{2}f''(x)h^2+\dots$$

Entonces, tomando la aproximación de primer orden:

$$f(x+h)-f(x) \approx f'(x)h$$

Lo cual, reemplazando con $x=783$ y $h=1$:

$$28-\sqrt{783} \approx \frac{1}{2\sqrt{783}}$$

Para una aproximación de segundo orden:

$$f(x+h)-f(x) \approx f'(x)h + \frac{1}{2}f''(x)h^2$$

Entonces:

$$28-\sqrt{783} \approx \frac{1}{2\sqrt{783}} - \frac{1}{4\cdot783^{3/2}}$$

Veremos como cambia el error relativo con ambas aproximaciones. Notemos que con esta última aproximación hay una resta!

In [6]:
x22 = 0.5/27.982
print("Error absoluto raíz 2: ")
print(f"{abs(raiz_2-x22):.2e}")

print("\nError relativo raíz 2: ")
print(f"{abs(raiz_2-x22)/abs(raiz_2):.2e}")

Error absoluto raíz 2: 
5.79e-06

Error relativo raíz 2: 
3.24e-04


In [7]:
x23 = (0.5/27.982) - (0.25)/(27.982**3)

print("Error absoluto raíz 2: ")
print(f"{abs(raiz_2-x23):.2e}")

print("\nError relativo raíz 2: ")
print(f"{abs(raiz_2-x23)/abs(raiz_2):.2e}")

Error absoluto raíz 2: 
5.62e-06

Error relativo raíz 2: 
3.15e-04


### Escriba una rutina que calcule las raíces de un polinomio de grado 2 con menor error relativo

In [12]:
def calculator(a, b, c, dec=3):
    """
    input:  coeficientes a, b y c de un polinomio
            p(x) = ax^2 + bx + c
    output: raíces x1, x2
    """
    delta = np.around(np.sqrt(b**2 - 4*a*c), decimals=dec)
    x1 = (-b + delta)/(2*a)
    x2 = c/x1
    return x1, x2

In [15]:
x1, x2 = calculator(1, -56, 1, dec=2)

print("Error absoluto raíz 1: ")
print(f"{abs(raiz_1-x1):.2e}")

print("\nError relativo raíz 1: ")
print(f"{abs(raiz_1-x1)/abs(raiz_1):.2e}")

print("\nError absoluto raíz 2:")
print(f"{abs(raiz_2-x2):.2e}")

print("\nError relativo raíz 2: ")
print(f"{abs(raiz_2-x2)/abs(raiz_2):.2e}")

Error absoluto raíz 1: 
2.14e-03

Error relativo raíz 1: 
3.82e-05

Error absoluto raíz 2:
6.82e-07

Error relativo raíz 2: 
3.82e-05


## Problema 2

Estime una cota para el backward error generado al calcular la solución del siguiente sistema:

$$\begin{pmatrix}2&1\\3&6\end{pmatrix}x=\begin{pmatrix}5.224\\21.357\end{pmatrix}$$

cuando por medio de un algoritmo se obtuvo la siguiente solución computada:

$$x_c = \begin{pmatrix}1\\3\end{pmatrix}$$

Aquí, podemos ver que tan buena es la aproximación $x_c$ simplemente poniendo esta donde aparece $x$. Así:

$$\|Ax_c-b\| = \|r\|$$

mide el error obtenido por la aproximación obtenida por el algoritmo externo. Se mide entonces este para obtener una cota para el backward error:

In [22]:
A = np.array([[2, 1], [3, 6]])
b = np.array([5.224, 21.357])

xc = np.array([1, 3])

print(f"Cota de backward error: {np.linalg.norm(A@xc-b, 2):.2f}")

Cota de backward error: 0.42


## Problema 3: Perturbación de la matriz identidad

Sea $E$ una matriz cuadrada.

### Muestre que si (I-E) es invertible, entonces:

$$\frac{\|(I-E)^{-1}-I\|}{\|(I-E)^{-1}\|}\leq \|E\|$$

Como $(I-E)$ invertible, podemos escribir:

$$\begin{align*}E &= I - (I-E)\\ &= (I-E)((I-E)^{-1}-I) \end{align*}$$

Multiplicamos esta ecuación por la izquierda por $(I-E)^{-1}$ y obtenemos:

$$(I-E)^{-1}E = (I-E)^{-1}-I$$

De esta forma:

$$\|(I-E)^{-1}-I\|=\|(I-E)^{-1}E\|\leq \|(I-E)^{-1}\|\|E\|$$

De donde es fácil obtener la desigualdad pedida.

### Muestre que :

$$\frac{1}{1+\|E\|}\leq \|(I-E)^{-1}\|$$

Con la parte anterior, tenemos que:

$$\begin{align*}
\|(I-E)^{-1}\|&\geq \frac{\|(I-E)^{-1}-I\|}{\|E\|}\\
&= \frac{\|(I-E)^{-1}-I\|}{\|E\|}\cdot\frac{\|I-E\|}{\|I-E\|}\\
&\geq\frac{\|E\|}{\|E\|\|I-E\|}\\
&= \frac{1}{\|I-E\|}
\end{align*}$$

2do paso:

$$\|E\| = \|I - (I-E)\| = \|(I-E)((I-E)^{-1} - I)\|\leq \|I-E\|\|(I-E)^{-1}-I\|$$

Recordamos que:

$$\|I-E\|\leq \|I\| + \|E\| = 1+\|E\|$$

Así, aplicando esta desigualdad tenemos que:

$$\frac{1}{1+\|E\|}\leq \|(I-E)^{-1}\|$$




### Haga un programa que muestre estas cotas

In [27]:
import pandas as pd

In [54]:
#Lazy functions. Podríamos reportar en una tabla!! ¿Cómo lo harían?

def cota_1(n, p):
    
    E = np.random.random(size=(n,n))/1000
    I = np.identity(n)
    I_E_inv = np.linalg.inv(I-E)
    
    norma_E = np.linalg.norm(E, ord=p)
    norma_I_E_I = np.linalg.norm(I_E_inv - I, ord=p)
    norma_I_E = np.linalg.norm(I_E_inv, ord=p)
    
    l_izq = norma_I_E_I/norma_I_E
    l_der = norma_E
    
    #print(f"lado_izquierdo: {l_izq:.3f}")
    #print(f"lado_derecho: {l_der:.3f}")
    #print(f"Se cumple? {l_izq <= l_der}")
    
    return l_izq, l_der

def cota_2(n, p):
    
    E = np.random.random(size=(n,n))/1000
    I = np.identity(n)
    I_E_inv = np.linalg.inv(I-E)
    
    print(E)
    
    norma_E = np.linalg.norm(E, ord=p)
    norma_I_E = np.linalg.norm(I_E_inv, ord=p)
    
    l_izq = 1/(1+norma_E)
    l_der = norma_I_E
    
    #print(f"lado_izquierdo: {l_izq:.3f}")
    #print(f"lado_derecho: {l_der:.3f}")
    #print(f"Se cumple? {l_izq <= l_der}")
    
    return l_izq, l_der


def rutina_2(n):
    
    normas = [1, 2, np.inf] #indices
    cota_1_izq, cota_1_der = [], []
    cota_2_izq, cota_2_der = [], []
    
    for p in normas:
        lic1, ldc1 = cota_1(n, p)
        lic2, ldc2 = cota_2(n, p)
        cota_1_izq.append(lic1)
        cota_1_der.append(ldc1)
        cota_2_izq.append(lic2)
        cota_2_der.append(ldc2)
        
    tabla = pd.DataFrame(data={"p":normas, 
                               "Cota 1 izq": cota_1_izq,
                               "Cota 1 der": cota_1_der,
                               "True?": np.array(cota_1_izq)<=np.array(cota_1_der),
                               "Cota 2 izq": cota_2_izq,
                               "Cota 2 der": cota_2_der,
                               "True_2?": np.array(cota_2_izq)<=np.array(cota_2_der)})
    return tabla
    

In [55]:
rutina_2(2)

[[0.00013544 0.00095427]
 [0.00013048 0.0008721 ]]
[[0.00021591 0.00011575]
 [0.0002467  0.00043843]]
[[0.00067206 0.00069819]
 [0.0009383  0.0003229 ]]


p  Cota 1 izq  Cota 1 der  True?  Cota 2 izq  Cota 2 der  True_2?
0  1.0    0.000874    0.000874   True    0.998177    1.001828     True
1  2.0    0.000881    0.000881   True    0.999454    1.000540     True
2  inf    0.001983    0.001985   True    0.998632    1.001372     True